spring:
  datasource:
    url: jdbc:mysql://ib-db:3306/internetbanking?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true