spring:
  datasource:
    url: jdbc:mysql://mysql-db2:3306/internetbanking?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      generate-ddl: true
      ddl-auto: update